# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd3d3b8566c31e0ed96b4f4fdf9a7d416b6d9a1bd90ddc021bdd3b5f170bb1e7b0e1a7ac97488759f0812803b78a113a3debac0c65139d4ec6f4d1c06b0cebb

test:
  secret_key_base: 29ba50759afb7e216e6cea8f2bef45cf202ad799edd7fc7e3a65a397442dc039f4c7ade055d1f0d735d1b2a15023bcc427fcd76afb809b1dba7687db4fa2ec36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
